# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-13 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180111_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='ass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=20)),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
                ('update_data', models.DateTimeField(auto_now=True, error_messages={'invalid': '日期格式错误'})),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo_temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserType', models.CharField(choices=[('1', '普通用户'), ('2', '管理员'), ('3', '超级管理员')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
