# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-14 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_usertpye'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.ass'),
            preserve_default=False,
        ),
    ]
