# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-18 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20180114_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=20)),
            ],
        ),
    ]
